listener {
    timeout = 240
    on-timeout = brightnessctl -s set 2%
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
